services:
  - type: web
    name: careeropen-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn careeropen.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "careeropen-api.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://frontend-i6yrnbsn5-reuben-idans-projects.vercel.app"